package com.fmart.hibernate.pojos;

// Generated Apr 19, 2015 7:02:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DbBackupJob generated by hbm2java
 */
@Entity
@Table(name = "db_backup_job", schema = "fmart")
public class DbBackupJob implements java.io.Serializable {

	private int id;
	private String cronName;
	private String directory;
	private String status;
	private Date startts;
	private Date endts;
	private String fullBckFilename;
	private String prodBckFilename;

	public DbBackupJob() {
	}

	public DbBackupJob(int id) {
		this.id = id;
	}

	public DbBackupJob(int id, String cronName, String directory,
			String status, Date startts, Date endts, String fullBckFilename,
			String prodBckFilename) {
		this.id = id;
		this.cronName = cronName;
		this.directory = directory;
		this.status = status;
		this.startts = startts;
		this.endts = endts;
		this.fullBckFilename = fullBckFilename;
		this.prodBckFilename = prodBckFilename;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "cron_name", length = 100)
	public String getCronName() {
		return this.cronName;
	}

	public void setCronName(String cronName) {
		this.cronName = cronName;
	}

	@Column(name = "directory", length = 200)
	public String getDirectory() {
		return this.directory;
	}

	public void setDirectory(String directory) {
		this.directory = directory;
	}

	@Column(name = "status", length = 50)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "startts", length = 35)
	public Date getStartts() {
		return this.startts;
	}

	public void setStartts(Date startts) {
		this.startts = startts;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "endts", length = 35)
	public Date getEndts() {
		return this.endts;
	}

	public void setEndts(Date endts) {
		this.endts = endts;
	}

	@Column(name = "full_bck_filename", length = 100)
	public String getFullBckFilename() {
		return this.fullBckFilename;
	}

	public void setFullBckFilename(String fullBckFilename) {
		this.fullBckFilename = fullBckFilename;
	}

	@Column(name = "prod_bck_filename", length = 100)
	public String getProdBckFilename() {
		return this.prodBckFilename;
	}

	public void setProdBckFilename(String prodBckFilename) {
		this.prodBckFilename = prodBckFilename;
	}

}
