package com.fmart.hibernate.pojos;

// Generated Mar 22, 2015 12:59:42 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.codehaus.jackson.annotate.JsonBackReference;
import org.codehaus.jackson.annotate.JsonManagedReference;
/**
 * EmpReport generated by hbm2java
 */
@Entity
@Table(name = "emp_report", schema = "fmart")
public class EmpReport implements java.io.Serializable {

	private int id;
	private Employee employee;
	private Report report;

	

	public EmpReport() {
	}

	public EmpReport(int id) {
		this.id = id;
	}

	public EmpReport(int id, Employee employee, Report report) {
		this.id = id;
		this.employee = employee;
		this.report = report;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	 @JsonBackReference@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "emp_id")
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	 @JsonBackReference@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "report_id")
	public Report getReport() {
		return this.report;
	}

	public void setReport(Report report) {
		this.report = report;
	}

}
