package com.fmart.hibernate.pojos;

// Generated Mar 22, 2015 7:04:02 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.codehaus.jackson.annotate.JsonBackReference;
import org.codehaus.jackson.annotate.JsonManagedReference;
/**
 * EmpRole generated by hbm2java
 */
@Entity
@Table(name = "emp_role", schema = "fmart")
public class EmpRole implements java.io.Serializable {

	private int id;
	private Employee employee;
	private Roles roles;

	public EmpRole() {
	}

	public EmpRole(int id) {
		this.id = id;
	}

	public EmpRole(int id, Employee employee, Roles roles) {
		this.id = id;
		this.employee = employee;
		this.roles = roles;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	 @JsonBackReference@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "emp_id")
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	 @JsonBackReference@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "role_id")
	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

}
