package com.fmart.hibernate.pojos;

// Generated Mar 19, 2015 11:56:59 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlTransient;

import org.codehaus.jackson.annotate.JsonBackReference;
import org.codehaus.jackson.annotate.JsonIgnore;
import org.codehaus.jackson.annotate.JsonManagedReference;

/**
 * Expense generated by hbm2java
 */
@Entity
@Table(name = "expense", schema = "fmart")
public class Expense implements java.io.Serializable, Comparable<Expense> {

	private int id;
	private Employee employeeByEmployeeId = new Employee();
	private Company company = new Company();
	private ExpenseType expenseType;

	private String particulars;
	private Integer amount;

	private String employeeByEmployeeId_name;
	private String company_name;
	private String employeeByUpdatedBy_name;
	private String employeeByCreatedBy_name;
	private String expenseType_name;

	public Expense() {

		this.created = new Date();
	}

	public Expense(int id) {
		this.id = id;
	}

	public Expense(int id, Employee employeeByCreatedBy,
			Employee employeeByEmployeeId, Company company,
			ExpenseType expenseType,  Integer type_id,
			String particulars, Integer amount) {
		this.id = id;
		this.employeeByEmployeeId = employeeByEmployeeId;
		this.company = company;
		this.expenseType = expenseType;
		this.particulars = particulars;
		this.amount = amount;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "employee_id")
	public Employee getEmployeeByEmployeeId() {
		return this.employeeByEmployeeId;
	}

	public void setEmployeeByEmployeeId(Employee employeeByEmployeeId) {
		this.employeeByEmployeeId = employeeByEmployeeId;
		if (employeeByEmployeeId == null || employeeByEmployeeId.getId() == 0)
			this.employeeByEmployeeId_name = "";
		else
			this.employeeByEmployeeId_name = employeeByEmployeeId.getName();
	}

	@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "company_id")
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
		this.company_name = company.getName();
	}

	@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "type_id")
	public ExpenseType getExpenseType() {
		return expenseType;
	}

	public void setExpenseType(ExpenseType expenseType) {
		this.expenseType = expenseType;
		this.expenseType_name = expenseType.getName();
	}

	@Column(name = "particulars", length = 50)
	public String getParticulars() {
		return this.particulars;
	}

	public void setParticulars(String particulars) {
		this.particulars = particulars;
	}

	@Column(name = "amount")
	public Integer getAmount() {
		return this.amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	private Employee employeeByUpdatedBy;
	private Employee employeeByCreatedBy;
	private Date created;
	private Date updated;

	@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "created_by")
	public Employee getEmployeeByCreatedBy() {
		return this.employeeByCreatedBy;
	}

	public void setEmployeeByCreatedBy(Employee employeeByCreatedBy) {
		this.employeeByCreatedBy = employeeByCreatedBy;
		this.employeeByCreatedBy_name = employeeByCreatedBy.getName();
	}

	@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "updated_by")
	public Employee getEmployeeByUpdatedBy() {
		return this.employeeByUpdatedBy;
	}

	public void setEmployeeByUpdatedBy(Employee employeeByUpdatedBy) {
		this.employeeByUpdatedBy = employeeByUpdatedBy;
		this.employeeByUpdatedBy_name = employeeByUpdatedBy.getName();
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", length = 35)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", length = 35)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Override
	public int compareTo(Expense o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Transient
	@XmlTransient
	@JsonIgnore
	public String getEmployeeByEmployeeId_name() {
		return employeeByEmployeeId_name;
	}

	public void setEmployeeByEmployeeId_name(String employeeByEmployeeId_name) {
		this.employeeByEmployeeId_name = employeeByEmployeeId_name;
	}

	@Transient
	@XmlTransient
	@JsonIgnore
	public String getCompany_name() {
		return company_name;
	}

	public void setCompany_name(String company_name) {
		this.company_name = company_name;
	}

	@Transient
	@XmlTransient
	@JsonIgnore
	public String getEmployeeByUpdatedBy_name() {
		return employeeByUpdatedBy_name;
	}

	public void setEmployeeByUpdatedBy_name(String employeeByUpdatedBy_name) {
		this.employeeByUpdatedBy_name = employeeByUpdatedBy_name;
	}

	@Transient
	@XmlTransient
	@JsonIgnore
	public String getEmployeeByCreatedBy_name() {
		return employeeByCreatedBy_name;
	}

	public void setEmployeeByCreatedBy_name(String employeeByCreatedBy_name) {
		this.employeeByCreatedBy_name = employeeByCreatedBy_name;
	}

	@Transient
	@XmlTransient
	@JsonIgnore
	public String getExpenseType_name() {
		return expenseType_name;
	}

	public void setExpenseType_name(String expenseType_name) {
		this.expenseType_name = expenseType_name;
	}

}