package com.fmart.hibernate.pojos;

// Generated May 27, 2015 6:00:14 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GodownInventoryId generated by hbm2java
 */
@Embeddable
public class GodownInventoryId implements java.io.Serializable {

	private int productId;
	private int godownId;
	private boolean customised;

	public GodownInventoryId() {
	}

	public GodownInventoryId(int productId, int godownId, boolean customised) {
		this.productId = productId;
		this.godownId = godownId;
		this.customised = customised;
	}

	@Column(name = "product_id", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	@Column(name = "godown_id", nullable = false)
	public int getGodownId() {
		return this.godownId;
	}

	public void setGodownId(int godownId) {
		this.godownId = godownId;
	}

	@Column(name = "customised", nullable = false)
	public boolean isCustomised() {
		return this.customised;
	}

	public void setCustomised(boolean customised) {
		this.customised = customised;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GodownInventoryId))
			return false;
		GodownInventoryId castOther = (GodownInventoryId) other;

		return (this.getProductId() == castOther.getProductId())
				&& (this.getGodownId() == castOther.getGodownId())
				&& (this.isCustomised() == castOther.isCustomised());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProductId();
		result = 37 * result + this.getGodownId();
		result = 37 * result + (this.isCustomised() ? 1 : 0);
		return result;
	}

}
