package com.fmart.hibernate.pojos;

// Generated May 26, 2015 4:15:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.codehaus.jackson.annotate.JsonBackReference;

/**
 * Godown generated by hbm2java
 */
@Entity
@Table(name = "godown", schema = "fmart")
public class Godown implements java.io.Serializable {

	private Integer id;
	private Employee employeeByCreatedBy;
	private Employee employeeByUpdatedBy;
	private Company company = new Company();
	private String name;
	private String address;
	private Date created;
	private Date updated;
	private Set<GodownInventory> godownInventories = new HashSet<GodownInventory>(
			0);
	
	private int inventoryInHand;
	
	@Transient
	public int getInventoryInHand() {
		return inventoryInHand;
	}

	public void setInventoryInHand(int inventoryInHand) {
		this.inventoryInHand = inventoryInHand;
	}

	public Godown() {
	}

	public Godown(Integer id) {
		this.id = id;
	}

	public Godown(Integer id, Employee employeeByCreatedBy,
			Employee employeeByUpdatedBy, Company company, String name,
			String address, Date created, Date updated,
			Set<GodownInventory> godownInventories) {
		this.id = id;
		this.employeeByCreatedBy = employeeByCreatedBy;
		this.employeeByUpdatedBy = employeeByUpdatedBy;
		this.company = company;
		this.name = name;
		this.address = address;
		this.created = created;
		this.updated = updated;
		this.godownInventories = godownInventories;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "created_by")
	public Employee getEmployeeByCreatedBy() {
		return this.employeeByCreatedBy;
	}

	public void setEmployeeByCreatedBy(Employee employeeByCreatedBy) {
		this.employeeByCreatedBy = employeeByCreatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "updated_by")
	public Employee getEmployeeByUpdatedBy() {
		return this.employeeByUpdatedBy;
	}

	public void setEmployeeByUpdatedBy(Employee employeeByUpdatedBy) {
		this.employeeByUpdatedBy = employeeByUpdatedBy;
	}

	@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "company_id")
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	@Column(name = "name", length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "address", length = 50)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", length = 35)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", length = 35)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "godown")
	public Set<GodownInventory> getGodownInventories() {
		return this.godownInventories;
	}

	public void setGodownInventories(Set<GodownInventory> godownInventories) {
		this.godownInventories = godownInventories;
	}

}
