package com.fmart.hibernate.pojos;

// Generated May 27, 2015 6:18:42 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * GodownInventory generated by hbm2java
 */
@Entity
@Table(name = "godown_inventory", schema = "fmart")
public class GodownInventory implements java.io.Serializable {

	private GodownInventoryId id = new GodownInventoryId();
	private Godown godown;
	private Product product;
	private Integer count;

	public GodownInventory() {
	}

	public GodownInventory(GodownInventoryId id, Godown godown, Product product) {
		this.id = id;
		this.godown = godown;
		this.product = product;
	}

	public GodownInventory(GodownInventoryId id, Godown godown,
			Product product, Integer count) {
		this.id = id;
		this.godown = godown;
		this.product = product;
		this.count = count;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "productId", column = @Column(name = "product_id", nullable = false)),
			@AttributeOverride(name = "godownId", column = @Column(name = "godown_id", nullable = false)),
			@AttributeOverride(name = "customised", column = @Column(name = "customised", nullable = false)) })
	public GodownInventoryId getId() {
		return this.id;
	}

	public void setId(GodownInventoryId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "godown_id", nullable = false, insertable = false, updatable = false)
	public Godown getGodown() {
		return this.godown;
	}

	public void setGodown(Godown godown) {
		this.godown = godown;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false, insertable = false, updatable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "count")
	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

}
