package com.fmart.hibernate.pojos;

// Generated Mar 19, 2015 11:56:59 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InventoryId generated by hbm2java
 */
@Embeddable
public class InventoryId implements java.io.Serializable {

	private int productId;
	private int companyId;
	private boolean customised;

	public InventoryId() {
	}

	public InventoryId(int productId, int companyId, boolean customised) {
		this.productId = productId;
		this.companyId = companyId;
		this.customised = customised;
	}

	@Column(name = "product_id", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	@Column(name = "company_id", nullable = false)
	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

	@Column(name = "customised", nullable = false)
	public boolean isCustomised() {
		return this.customised;
	}

	public void setCustomised(boolean customised) {
		this.customised = customised;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InventoryId))
			return false;
		InventoryId castOther = (InventoryId) other;

		return (this.getProductId() == castOther.getProductId())
				&& (this.getCompanyId() == castOther.getCompanyId())
				&& (this.isCustomised() == castOther.isCustomised());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProductId();
		result = 37 * result + this.getCompanyId();
		result = 37 * result + (this.isCustomised() ? 1 : 0);
		return result;
	}

}
