package com.fmart.hibernate.pojos;

// Generated Mar 29, 2015 2:30:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Notifications generated by hbm2java
 */
@Entity
@Table(name = "notifications", schema = "fmart")
public class Notifications implements java.io.Serializable {

	private int id;
	private String fromVal;
	private String toVal;
	private String type;
	private String updateBy;
	private String action;
	private Date date;

	
	public Notifications() {
		
		this.date= new Date();
	}

	public Notifications(int id) {
		this.id = id;
	}

	public Notifications(int id, String fromVal,Date date, String toVal, String type,
			String updateBy,String action) {
		this.id = id;
		this.fromVal = fromVal;
		this.date = date;
		this.toVal = toVal;
		this.type = type.toUpperCase();
		this.updateBy = updateBy;
		this.action = action;
	}
	public Notifications( String fromVal, String toVal, String type,
			String updateBy,String action) {
		
		this.fromVal = fromVal;
		this.toVal = toVal;
		this.type = type.toUpperCase();
		this.updateBy = updateBy;
		this.action = action;
		this.date = new Date();
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "from_val", length = 5000)
	public String getFromVal() {
		return this.fromVal;
	}

	public void setFromVal(String fromVal) {
		this.fromVal = fromVal;
	}

	@Column(name = "to_val", length = 5000)
	public String getToVal() {
		return this.toVal;
	}

	public void setToVal(String toVal) {
		this.toVal = toVal;
	}

	@Column(name = "type", length = 30)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "update_by", length = 50)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}
	@Column(name = "action", length = 50)
	public String getAction() {
		return action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", length = 29)
	public Date getDate() {
		return this.date;
	}
	
	public void setDate(Date date) {
		this.date = date;
	}
	
	


}
