package com.fmart.hibernate.pojos;

// Generated Mar 19, 2015 11:56:59 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlTransient;

import org.codehaus.jackson.annotate.JsonBackReference;
import org.codehaus.jackson.annotate.JsonIgnore;
import org.codehaus.jackson.annotate.JsonManagedReference;

/**
 * Payment generated by hbm2java
 */
@Entity
@Table(name = "payment", schema = "fmart")
public class Payment implements java.io.Serializable, Comparable<Payment> {

	private int id;
	private Company company;
	private Dealer dealer;
	private BigDecimal amount;

	private String company_name;
	private String dealer_name;
	private String employeeByCreatedBy_name;
	private String employeeByUpdatedBy_name;

	public Payment() {

		this.created = new Date();
	}

	public Payment(int id) {
		this.id = id;
	}

	public Payment(int id, Employee employee, Company company, Dealer dealer,
			BigDecimal amount) {
		this.id = id;
		this.company = company;
		this.dealer = dealer;
		this.amount = amount;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "company_id")
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
		this.company_name = company.getName();
	}

	@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dealer_id")
	public Dealer getDealer() {
		return this.dealer;
	}

	public void setDealer(Dealer dealer) {
		this.dealer = dealer;
		this.dealer_name = dealer.getName();
	}

	@Column(name = "amount", precision = 10)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}


	private Employee employeeByUpdatedBy;
	private Employee employeeByCreatedBy;
	private Date created;
	private Date updated;

	@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "created_by")
	public Employee getEmployeeByCreatedBy() {
		return this.employeeByCreatedBy;
	}

	public void setEmployeeByCreatedBy(Employee employeeByCreatedBy) {
		this.employeeByCreatedBy = employeeByCreatedBy;
		this.employeeByCreatedBy_name = employeeByCreatedBy.getName();
	}

	@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "updated_by")
	public Employee getEmployeeByUpdatedBy() {
		return this.employeeByUpdatedBy;
	}

	public void setEmployeeByUpdatedBy(Employee employeeByUpdatedBy) {
		this.employeeByUpdatedBy = employeeByUpdatedBy;
		this.employeeByUpdatedBy_name = employeeByUpdatedBy.getName();
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", length = 35)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", length = 35)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Override
	public int compareTo(Payment o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Transient
	@XmlTransient
	@JsonIgnore
	public String getCompany_name() {
		return company_name;
	}

	public void setCompany_name(String company_name) {
		this.company_name = company_name;
	}

	@Transient
	@XmlTransient
	@JsonIgnore
	public String getDealer_name() {
		return dealer_name;
	}

	public void setDealer_name(String dealer_name) {
		this.dealer_name = dealer_name;
	}

	@Transient
	@XmlTransient
	@JsonIgnore
	public String getEmployeeByCreatedBy_name() {
		return employeeByCreatedBy_name;
	}

	public void setEmployeeByCreatedBy_name(String employeeByCreatedBy_name) {
		this.employeeByCreatedBy_name = employeeByCreatedBy_name;
	}

	@Transient
	@XmlTransient
	@JsonIgnore
	public String getEmployeeByUpdatedBy_name() {
		return employeeByUpdatedBy_name;
	}

	public void setEmployeeByUpdatedBy_name(String employeeByUpdatedBy_name) {
		this.employeeByUpdatedBy_name = employeeByUpdatedBy_name;
	}

}
