package com.fmart.hibernate.pojos;

// Generated Mar 19, 2015 11:56:59 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlTransient;

import org.codehaus.jackson.annotate.JsonBackReference;
import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * PurchaseDetail generated by hbm2java
 */
@Entity
@Table(name = "purchase_detail", schema = "fmart")
public class PurchaseDetail implements java.io.Serializable {

	private int id;
	private Purchase purchase;
	private Product product;
	private Integer quantity;
	private Integer ret_quantity;
	private BigDecimal amount;
	private String remarks;
	private Boolean returned;
	private BigDecimal rate;
	private Boolean customised;

	public PurchaseDetail() {
		
		this.created= new Date();
	}

	public PurchaseDetail(int id) {
		this.id = id;
	}

	public PurchaseDetail(int id, Purchase purchase, Product product,
			Integer quantity, BigDecimal amount, String remarks,BigDecimal rate,
			Boolean returned,Boolean customised) {
		this.id = id;
		this.purchase = purchase;
		this.product = product;
		this.quantity = quantity;
		this.amount = amount;
		this.remarks = remarks;
		this.returned = returned;
		this.customised = customised;
		this.rate = rate;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@JsonBackReference@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "purchase_id")
	public Purchase getPurchase() {
		return this.purchase;
	}

	public void setPurchase(Purchase purchase) {
		this.purchase = purchase;
	}

	@JsonBackReference@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id")
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Transient
	@XmlTransient
	@JsonIgnore
	public Integer getRet_quantity() {
		return ret_quantity;
	}

	public void setRet_quantity(Integer ret_quantity) {
		this.ret_quantity = ret_quantity;
	}

	@Column(name = "amount", precision = 10)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "remarks", length = 50)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "returned")
	public Boolean getReturned() {
		if(this.returned==null || !this.returned)
			return false;
		return this.returned;
	}

	public void setReturned(Boolean returned) {
		this.returned = returned;
	}
	
	@Column(name = "customised")
	public Boolean getCustomised() {
		if(this.customised==null || !this.customised)
			return false;
		return this.customised;
	}

	public void setCustomised(Boolean customised) {
		this.customised = customised;
	}

	@Column(name = "rate", precision = 10)
	public BigDecimal getRate() {
		return this.rate;
	}

	public void setRate(BigDecimal rate) {
		this.rate = rate;
	}
	
	private Employee employeeByUpdatedBy;
	private Employee employeeByCreatedBy;
	private Date created;
	private Date updated;

	@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "created_by")
	public Employee getEmployeeByCreatedBy() {
		return this.employeeByCreatedBy;
	}

	public void setEmployeeByCreatedBy(Employee employeeByCreatedBy) {
		this.employeeByCreatedBy = employeeByCreatedBy;
	}

	@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "updated_by")
	public Employee getEmployeeByUpdatedBy() {
		return this.employeeByUpdatedBy;
	}

	public void setEmployeeByUpdatedBy(Employee employeeByUpdatedBy) {
		this.employeeByUpdatedBy = employeeByUpdatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", length = 35)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", length = 35)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}
}
