package com.fmart.hibernate.pojos;

// Generated Mar 19, 2015 11:56:59 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.concurrent.TimeUnit;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlTransient;

import org.codehaus.jackson.annotate.JsonBackReference;
import org.codehaus.jackson.annotate.JsonIgnore;
import org.codehaus.jackson.annotate.JsonManagedReference;

/**
 * Purchase generated by hbm2java
 */
@Entity
@Table(name = "purchase", schema = "fmart")
public class Purchase implements java.io.Serializable, Comparable<Purchase> {

	private int id;

	private Dealer dealer;
	private Company company;
	private String status;
	private BigDecimal amount;
	private String description;
	private List<PurchaseDetail> purchaseDetails = new ArrayList<PurchaseDetail>();

	private String dealer_name;
	private String company_name;
	private String employeeByUpdatedBy_name;
	private String employeeByCreatedBy_name;

	private boolean updateable = false;

	public Purchase() {

		this.created = new Date();
	}

	public Purchase(int id) {
		this.id = id;
	}

	public Purchase(int id, Employee employeeByCreatedBy,
			Employee employeeByEmployeeId, Dealer dealer, Company company,
			String status, BigDecimal amount, String description,
			List<PurchaseDetail> purchaseDetails) {
		this.id = id;

		this.dealer = dealer;
		this.company = company;
		this.status = status;
		this.amount = amount;
		this.purchaseDetails = purchaseDetails;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dealer_id")
	public Dealer getDealer() {
		return this.dealer;
	}

	public void setDealer(Dealer dealer) {
		this.dealer = dealer;
		this.dealer_name = dealer.getName();
	}

	@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "company_id")
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
		this.company_name = company.getName();
	}

	@Column(name = "status", length = 15)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "amount", precision = 10)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "description", length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		if(description!=null &&  description.length()>=50)
			this.description = description.substring(0, 50);
		else
			this.description = description;
	}

	@JsonManagedReference
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "purchase", cascade = { CascadeType.ALL })
	public List<PurchaseDetail> getPurchaseDetails() {
		return this.purchaseDetails;
	}

	public void setPurchaseDetails(List<PurchaseDetail> purchaseDetails) {
		if (purchaseDetails != null)
			for (PurchaseDetail purchaseDetail : purchaseDetails)
				purchaseDetail.setPurchase(this);
		this.purchaseDetails = purchaseDetails;
	}

	private Employee employeeByUpdatedBy;
	private Employee employeeByCreatedBy;
	private Date created;
	private Date updated;

	@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "created_by")
	public Employee getEmployeeByCreatedBy() {
		return this.employeeByCreatedBy;
	}

	public void setEmployeeByCreatedBy(Employee employeeByCreatedBy) {
		this.employeeByCreatedBy = employeeByCreatedBy;
		this.employeeByCreatedBy_name = employeeByCreatedBy.getName();
	}

	@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "updated_by")
	public Employee getEmployeeByUpdatedBy() {
		return this.employeeByUpdatedBy;
	}

	public void setEmployeeByUpdatedBy(Employee employeeByUpdatedBy) {
		this.employeeByUpdatedBy = employeeByUpdatedBy;
		this.employeeByUpdatedBy_name = employeeByUpdatedBy.getName();
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", length = 35)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", length = 35)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Override
	public int compareTo(Purchase o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Transient
	@XmlTransient
	@JsonIgnore
	public String getDealer_name() {
		return dealer_name;
	}

	public void setDealer_name(String dealer_name) {
		this.dealer_name = dealer_name;
	}

	@Transient
	@XmlTransient
	@JsonIgnore
	public String getCompany_name() {
		return company_name;
	}

	public void setCompany_name(String company_name) {
		this.company_name = company_name;
	}

	@Transient
	@XmlTransient
	@JsonIgnore
	public String getEmployeeByUpdatedBy_name() {
		return employeeByUpdatedBy_name;
	}

	public void setEmployeeByUpdatedBy_name(String employeeByUpdatedBy_name) {
		this.employeeByUpdatedBy_name = employeeByUpdatedBy_name;
	}

	@Transient
	@XmlTransient
	@JsonIgnore
	public String getEmployeeByCreatedBy_name() {
		return employeeByCreatedBy_name;
	}

	public void setEmployeeByCreatedBy_name(String employeeByCreatedBy_name) {
		this.employeeByCreatedBy_name = employeeByCreatedBy_name;
	}

	@Transient
	@XmlTransient
	@JsonIgnore
	public boolean isUpdateable() {
		long diff = (new Date()).getTime() - created.getTime();
		if (TimeUnit.DAYS.convert(diff, TimeUnit.MILLISECONDS) > 90)
			return false;
		return true;
	}

	public void setUpdateable(boolean updateable) {
		this.updateable = updateable;
	}

}
