package com.fmart.hibernate.pojos;

// Generated Mar 19, 2015 11:56:59 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlTransient;

import org.codehaus.jackson.annotate.JsonBackReference;
import org.codehaus.jackson.annotate.JsonIgnore;
import org.codehaus.jackson.annotate.JsonManagedReference;

/**
 * Receipt generated by hbm2java
 */
@Entity
@Table(name = "receipt", schema = "fmart")
public class Receipt implements java.io.Serializable, Comparable<Receipt> {

	private int id;
	private Company company;
	private Sale sale;
	private BigDecimal amount;
	private String particulars;

	private String company_name;
	private String sale_customer_name;
	private String sale_customer_address;
	private String employeeByCreatedBy_name;
	private String employeeByUpdatedBy_name;

	public Receipt() {

		this.created = new Date();
	}

	public Receipt(int id) {
		this.id = id;
	}

	public Receipt(int id, Employee employee, Sale sale, 
			String particulars, BigDecimal amount) {
		this.id = id;
		this.sale = sale;
		this.amount = amount;
		this.particulars = particulars;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "company_id")
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
		this.company_name = company.getName();
	}

	@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sale_id")
	public Sale getSale() {
		return this.sale;
	}

	public void setSale(Sale sale) {
		this.sale = sale;
		this.sale_customer_name=sale.getCustomer().getName();
		this.sale_customer_address=sale.getCustomer().getAddress();
	}

	@Column(name = "particulars", length = 25)
	public String getParticulars() {
		return this.particulars;
	}

	public void setParticulars(String particulars) {
		this.particulars = particulars;
	}

	@Column(name = "amount", precision = 10)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	private Employee employeeByUpdatedBy;
	private Employee employeeByCreatedBy;
	private Date created;
	private Date updated;

	@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "created_by")
	public Employee getEmployeeByCreatedBy() {
		return this.employeeByCreatedBy;
	}

	public void setEmployeeByCreatedBy(Employee employeeByCreatedBy) {
		this.employeeByCreatedBy = employeeByCreatedBy;
		this.employeeByCreatedBy_name=employeeByCreatedBy.getName();
	}

	@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "updated_by")
	public Employee getEmployeeByUpdatedBy() {
		return this.employeeByUpdatedBy;
	}

	public void setEmployeeByUpdatedBy(Employee employeeByUpdatedBy) {
		this.employeeByUpdatedBy = employeeByUpdatedBy;
		this.employeeByUpdatedBy_name=employeeByUpdatedBy.getName();
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", length = 35)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", length = 35)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Override
	public int compareTo(Receipt o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Transient
	@XmlTransient
	@JsonIgnore
	public String getCompany_name() {
		return company_name;
	}

	public void setCompany_name(String company_name) {
		this.company_name = company_name;
	}

	@Transient
	@XmlTransient
	@JsonIgnore
	public String getSale_customer_name() {
		return sale_customer_name;
	}

	public void setSale_customer_name(String sale_customer_name) {
		this.sale_customer_name = sale_customer_name;
	}

	@Transient
	@XmlTransient
	@JsonIgnore
	public String getSale_customer_address() {
		return sale_customer_address;
	}

	public void setSale_customer_address(String sale_customer_address) {
		this.sale_customer_address = sale_customer_address;
	}

	@Transient
	@XmlTransient
	@JsonIgnore
	public String getEmployeeByCreatedBy_name() {
		return employeeByCreatedBy_name;
	}

	public void setEmployeeByCreatedBy_name(String employeeByCreatedBy_name) {
		this.employeeByCreatedBy_name = employeeByCreatedBy_name;
	}

	@Transient
	@XmlTransient
	@JsonIgnore
	public String getEmployeeByUpdatedBy_name() {
		return employeeByUpdatedBy_name;
	}

	public void setEmployeeByUpdatedBy_name(String employeeByUpdatedBy_name) {
		this.employeeByUpdatedBy_name = employeeByUpdatedBy_name;
	}

}
